server:
  port: 8082
spring:
  application:
    name: Attendance-Service
  config:
    import:
    - configserver:http://192.168.1.60:5050 
    
logging:
  level:
    root: INFO
  file:
    name: G:\HRMS_API\Attendance\app.log
 