server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://192.168.1.60:3306/attendance
    username: ankush
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: Attendance-Service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.60:8761/eureka/

logging:
  file:
    name: D:\New folder\myapp.log
attendance:
  monthly:
    csv:
      header: Sno, Employee Id, Employee Name, Month Name, Total Public Holiday, Total Working Day, Paid Leave, Employee Working Day
    